backend:
  name: "git-gateway"
  accept_roles:
    - "admin"
    - "editor"
media_folder: "static/images"
collections:
  - name: "pages"
    label: "Pages"
    folder: "site/pages"
    identifier_field: "title"
    extension: "md"
    create: false
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "{{slug}}.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
  - name: "place"
    label: "Places"
    folder: "site/place"
    create: true
    identifier_field: "name"
    extension: "md"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "place"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-place.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - name: "place-number"
        label: "Place number"
        widget: "number"
        required: false
      - widget: "object"
        name: "featured-artwork"
        label: "Featured workshop artwork"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - name: "quote"
        label: "Quote"
        widget: "string"
        required: false
      - name: "opening-hours"
        label: "Opening hours"
        widget: "string"
        required: false
      - name: "number-of-exhibitors"
        label: "Number of exhibitors"
        widget: "string"
        required: false
      - name: "additional-information"
        label: "Additional Information"
        widget: "string"
        required: false
      - widget: "relation"
        collection: "artist"
        value_field: "site/undefined/{{slug}}.md"
        search_fields:
          - "slug"
          - "name"
        display_fields:
          - "name"
        required: false
        multiple: true
        name: "artist-present"
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "artist"
    label: "Artists"
    folder: "site/artist"
    create: true
    identifier_field: "name"
    extension: "md"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "artist"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-artist.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - widget: "object"
        name: "featured-artwork"
        label: "Featured artwork"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - widget: "list"
        name: "artworks"
        label: "Artworks"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - name: "discipline"
        label: "Discipline"
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - name: "biography"
        label: "Biography"
        widget: "markdown"
        required: false
      - name: "mail"
        label: "Mail (Email)"
        widget: "string"
        required: false
      - name: "website-url"
        label: "Website url (URL)"
        widget: "string"
        required: false
      - name: "facebook-url"
        label: "Facebook url (URL)"
        widget: "string"
        required: false
      - name: "instagram-url"
        label: "Instagram url (URL)"
        widget: "string"
        required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
  - name: "index"
    label: "index"
    folder: "site/index"
    create: true
    identifier_field: "name"
    extension: "md"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Tags"
        widget: "hidden"
        name: "tags"
        default: "index"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Layout"
        widget: "hidden"
        name: "layout"
        default: "single-index.html"
      - label: "Seo"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
          - label: "Open Graph Image"
            name: "og:image"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - label: "Twitter Card"
            name: "twitter:card"
            widget: "string"
            default: "summary"
            required: false
          - label: "Twitter Site"
            name: "twitter:site"
            widget: "string"
            required: false
          - label: "Twitter Creator"
            name: "twitter:creator"
            widget: "string"
            required: false
          - label: "Additional HTML tags"
            name: "additional_tags"
            widget: "text"
            required: false
      - name: "edition"
        label: "Edition"
        widget: "string"
        required: false
      - name: "white-card-title"
        label: "White card title"
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - name: "concept"
        label: "Concept"
        widget: "markdown"
        required: false
      - name: "workshops"
        label: "Workshops"
        widget: "markdown"
        required: false
      - name: "info"
        label: "Info"
        widget: "markdown"
        required: false
      - widget: "object"
        name: "map"
        label: "Map"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - name: "partners"
        label: "Partners"
        widget: "markdown"
        required: false
      - widget: "object"
        name: "partner-1-logo"
        label: "Partner 1 logo"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - name: "partner-1-link"
        label: "Partner 1 link (URL)"
        widget: "string"
        required: false
      - widget: "object"
        name: "partner-2-logo"
        label: "Partner 2 logo"
        fields:
          - widget: "image"
            name: "url"
            label: "Image"
            allow_multiple: false
            required: false
          - widget: "string"
            name: "alt"
            label: "Alt Text"
            required: false
      - name: "partner-2-link"
        label: "Partner 2 link (URL)"
        widget: "string"
        required: false
      - name: "links"
        label: "Links"
        widget: "markdown"
        required: false
      - name: "name"
        label: "Name"
        widget: "string"
        required: true
      - name: "created-on"
        label: "Created On"
        widget: "datetime"
        required: false
      - name: "updated-on"
        label: "Updated On"
        widget: "datetime"
        required: false
      - name: "published-on"
        label: "Published On"
        widget: "datetime"
        required: false
